USE CONCESIONARIA
GO

/*
	CREACION DE ROLES
*/

CREATE ROLE ADMINISTRADORES
GO

CREATE ROLE CONSULTA
GO

CREATE ROLE EMPLEADO_AGENTE_VENTAS
GO


--user creado con user ADMINISTRADOR
CREATE ROLE EMPLEADO_TECNICO
GO

CREATE ROLE EMPLEADO_MECANICO
GO


/*
	Asignaci�n de permisos para rol ADMINISTRADORES
*/
EXEC sp_addrolemember 'db_owner', 'ADMINISTRADORES';

/*
	Asignaci�n de permisos para rol CONSULTA
*/

GRANT SELECT ON SCHEMA::VENTA TO CONSULTA;
GRANT SELECT ON SCHEMA::AVAL TO CONSULTA;
GRANT SELECT ON SCHEMA::CLIENTE TO CONSULTA;
GRANT SELECT ON SCHEMA::CATALOGO TO CONSULTA;
GRANT SELECT ON SCHEMA::EMPLEADO TO CONSULTA;
GRANT SELECT ON SCHEMA::SERVICIO TO CONSULTA;
GRANT SELECT ON SCHEMA::COCHE TO CONSULTA;





/*
	Asignaci�n de permisos para rol EMPLEADO_AGENTE_VENTAS
*/

-- VENTA
GRANT ALTER ON SCHEMA::VENTA TO EMPLEADO_AGENTE_VENTAS
GO
GRANT DELETE ON SCHEMA::VENTA TO EMPLEADO_AGENTE_VENTAS
GO
GRANT INSERT ON SCHEMA::VENTA TO EMPLEADO_AGENTE_VENTAS
GO
GRANT SELECT ON SCHEMA::VENTA TO EMPLEADO_AGENTE_VENTAS
GO
GRANT UPDATE ON SCHEMA::VENTA TO EMPLEADO_AGENTE_VENTAS
GO

-- CLIENTE
GRANT ALTER ON SCHEMA::CLIENTE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT DELETE ON SCHEMA::CLIENTE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT INSERT ON SCHEMA::CLIENTE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT SELECT ON SCHEMA::CLIENTE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT UPDATE ON SCHEMA::CLIENTE TO EMPLEADO_AGENTE_VENTAS
GO

--COCHE
GRANT ALTER ON SCHEMA::COCHE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT DELETE ON SCHEMA::COCHE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT INSERT ON SCHEMA::COCHE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT SELECT ON SCHEMA::COCHE TO EMPLEADO_AGENTE_VENTAS
GO
GRANT UPDATE ON SCHEMA::COCHE TO EMPLEADO_AGENTE_VENTAS
GO

--AVAL
GRANT ALTER ON SCHEMA::AVAL TO EMPLEADO_AGENTE_VENTAS
GO
GRANT DELETE ON SCHEMA::AVAL TO EMPLEADO_AGENTE_VENTAS
GO
GRANT INSERT ON SCHEMA::AVAL TO EMPLEADO_AGENTE_VENTAS
GO
GRANT SELECT ON SCHEMA::AVAL TO EMPLEADO_AGENTE_VENTAS
GO
GRANT UPDATE ON SCHEMA::AVAL TO EMPLEADO_AGENTE_VENTAS
GO


/*
	Asignaci�n de permisos para rol EMPLEADO_TECNICO
*/
--SERVICIO.SERVICIO
GRANT ALTER ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO
GRANT DELETE ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO
GRANT INSERT ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO
GRANT SELECT ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO
GRANT UPDATE ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO

--SERVICIO.REVISION
GRANT ALTER ON SERVICIO.REVISION TO EMPLEADO_TECNICO
GO
GRANT DELETE ON SERVICIO.REVISION TO EMPLEADO_TECNICO
GO
GRANT INSERT ON SERVICIO.REVISION TO EMPLEADO_TECNICO
GO
GRANT SELECT ON SERVICIO.REVISION TO EMPLEADO_TECNICO
GO
GRANT UPDATE ON SERVICIO.SERVICIO TO EMPLEADO_TECNICO
GO

/*
	Asignaci�n de permisos para rol EMPLEADO_MECANICO
*/

GRANT ALTER ON SCHEMA::SERVICIO TO EMPLEADO_MECANICO
GO
GRANT DELETE ON SCHEMA::SERVICIO TO EMPLEADO_MECANICO
GO
GRANT INSERT ON SCHEMA::SERVICIO TO EMPLEADO_MECANICO
GO
GRANT SELECT ON SCHEMA::SERVICIO TO EMPLEADO_MECANICO
GO
GRANT UPDATE ON SCHEMA::SERVICIO TO EMPLEADO_MECANICO
GO


/*

	CREACI�N DE USARIOS

*/

			/* USARIO ADMINISTRADOR */

--login
CREATE LOGIN ADMINISTRADOR WITH PASSWORD = '1234zaq*'
    MUST_CHANGE, CHECK_EXPIRATION = ON;
GO
--user
CREATE USER ADMINISTRADOR FOR LOGIN ADMINISTRADOR
GO
-- agregar al rol
ALTER ROLE ADMINISTRADORES ADD MEMBER ADMINISTRADOR
GO


ALTER SERVER ROLE securityadmin ADD MEMBER ADMINISTRADOR;--Permisos de creaci�n de LOGIN's

			/* USARIO AGENTE DE VENTAS VENTAS */
--Harvey_VENTAS
--'1234zaq*'

--login
CREATE LOGIN Harvey_VENTAS WITH PASSWORD = '1234zaq*', 
	CHECK_EXPIRATION = ON;
GO
--user
CREATE USER Harvey_VENTAS FOR LOGIN Harvey_VENTAS
GO
-- agregar al rol
ALTER ROLE EMPLEADO_AGENTE_VENTAS ADD MEMBER Harvey_VENTAS
GO

			/* USARIO MECANICO */
--Juan_MECANICO
--'1234zaq*'
--login
CREATE LOGIN Juan_MECANICO WITH PASSWORD = '1234zaq*', 
	CHECK_EXPIRATION = ON;
GO
--user
CREATE USER Juan_MECANICO FOR LOGIN Juan_MECANICO
GO
-- agregar al rol
ALTER ROLE EMPLEADO_MECANICO ADD MEMBER Juan_MECANICO
GO

			/* USARIO TECNICO */
--Angel_TECNICO
--'1234zaq*'
--login
CREATE LOGIN Angel_TECNICO WITH PASSWORD = '1234zaq*',
    CHECK_EXPIRATION = ON;
GO
--user
CREATE USER Angel_TECNICO FOR LOGIN Angel_TECNICO
GO
-- agregar al rol
ALTER ROLE EMPLEADO_TECNICO ADD MEMBER Angel_TECNICO
GO


/*
	usuarioConcesionario
*/


CREATE LOGIN usuarioConcesionario WITH PASSWORD = '1234zaq*',
    CHECK_EXPIRATION = ON;
GO
--user
CREATE USER usuarioConcesionario FOR LOGIN usuarioConcesionario
GO
-- agregar al rol
ALTER ROLE ADMINISTRADORES ADD MEMBER usuarioConcesionario
GO




                                  
CREATE SCHEMA ADMINISTRADOR
GO
                                  
CREATE OR ALTER FUNCTION ADMINISTRADOR.ValidarContrasena (@contrasena VARCHAR(100))
RETURNS VARCHAR(100)
AS
BEGIN
    DECLARE @resultado VARCHAR(100) = NULL;

    IF LEN(@contrasena) >= 10
    BEGIN
        IF PATINDEX('%[A-Za-z]%', @contrasena) > 0
        BEGIN
            IF PATINDEX('%[#$%&]%', @contrasena) > 0
            BEGIN
                IF PATINDEX('%[0-9]%', @contrasena) > 0
                BEGIN
                    SET @resultado = @contrasena;
                END
            END
        END
    END

    RETURN @resultado;
END;



